# Generated by Django 4.1.5 on 2023-01-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lokasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_tempat', models.CharField(max_length=100)),
                ('koordinat', models.CharField(max_length=150)),
                ('alamat', models.CharField(max_length=250)),
            ],
        ),
    ]
