# Generated by Django 4.1.5 on 2023-01-05 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_uas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='penduduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_kk', models.IntegerField(null=True)),
                ('jumlahl', models.IntegerField(null=True)),
                ('jumlahp', models.IntegerField(null=True)),
                ('jpenduduk', models.IntegerField(null=True)),
                ('lokasi_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_uas.lokasi')),
            ],
        ),
    ]
