# Generated by Django 4.1.5 on 2023-01-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_uas', '0002_penduduk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='penduduk',
            old_name='jumlahl',
            new_name='jumlahlk',
        ),
        migrations.RenameField(
            model_name='penduduk',
            old_name='jumlahp',
            new_name='jumlahpr',
        ),
    ]
