# Generated by Django 4.1.5 on 2023-01-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_uas', '0003_rename_jumlahl_penduduk_jumlahlk_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penduduk',
            name='lokasi_id',
        ),
    ]
