# Generated by Django 4.1.5 on 2023-01-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uas', '0004_remove_penduduk_lokasi_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_penduduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kk', models.CharField(max_length=50)),
                ('jumlah_lk', models.CharField(max_length=50)),
                ('jumlah_pr', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='penduduk',
        ),
    ]
