# Generated by Django 4.1.5 on 2023-01-05 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_uas', '0005_db_penduduk_delete_penduduk'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_penduduk',
            name='lokasi_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_uas.lokasi'),
        ),
    ]
