# Generated by Django 4.1.5 on 2023-01-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_uas', '0006_db_penduduk_lokasi_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lokasi',
            old_name='koordinat',
            new_name='garis_lintang',
        ),
    ]
